### ISSUE TITLE
implement Basemap instead of cartopy?

### ISSUE THREAD

**Issue by Swanson-Hysell** [ian-r-rose/mcplates#3]
Goal being that users don't have both Basemap and cartopy as dependencies.

Examples using pmagpy functions (ipmag) in Basemap for plotting poles+A95 and vgps are in this notebook: https://github.com/PmagPy/2016_Tauxe-et-al_PmagPy_Notebooks/blob/master/Example_PmagPy_Notebook.ipynb

For the sake of drawing poles, functions in ipmag make use of this method:
http://www.geophysique.be/2011/02/20/matplotlib-basemap-tutorial-09-drawing-circles/

```
def equi(m, centerlon, centerlat, radius, color):
    """
    This function enables A95 error ellipses to be drawn in basemap around paleomagnetic poles
    in conjunction with shoot
    (from: http://www.geophysique.be/2011/02/20/matplotlib-basemap-tutorial-09-drawing-circles/).
    """
```

```
def shoot(lon, lat, azimuth, maxdist=None):
    """
    This function enables A95 error ellipses to be drawn in basemap around paleomagnetic
    poles in conjunction with equi
    (from: http://www.geophysique.be/2011/02/20/matplotlib-basemap-tutorial-09-drawing-circles/)
    """
```

**Comment by ian-r-rose** [comment]
As basemap is being deprecated in favor of cartopy (https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement) I think it is safe to close this.

**Comment by Swanson-Hysell** [comment]
Yes indeed. We are now talking about making needing to make this transition to cartopy for PmagPy.
